name: Setup
description: Setup node, etc

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ">=20.16.0"
    - run: corepack enable
      shell: bash
    - run: corepack install
      shell: bash
    - run: yarn install --immutable
      shell: bash
