# https://yarnpkg.com/configuration/yarnrc

enableGlobalCache: true
nmMode: hardlinks-global

# For `node_modules` (see `nodeLinker` below), this is almost always the preferred option.
compressionLevel: 0

nodeLinker: node-modules
