const back = {
	type: "link",
	label: "← About the community",
	href: "/community",
};

const hr = { type: "html", value: "<hr/>" };

const gen = (dirName) => {
	return { type: "autogenerated", dirName };
};

export default {
	main: [gen("."), { type: "link", href: "/history", label: "History of BC" }],

	social: [back, hr, gen("social")],

	publishing: [
		{
			type: "link",
			label: "Publishing",
			href: "/publishing",
		},
		hr,
		gen("publishing"),
	],

	honours: [
		{
			type: "link",
			label: "← Lieutenant Governor",
			href: "/gov/lieutenant-governor",
		},
		hr,
		{
			type: "link",
			label: "Honours",
			href: "/honours",
		},
		gen("honours"),
	],
};
