const hr = { type: "html", value: "<hr/>" };

const back = {
	type: "link",
	label: "← About the community",
	href: "/community",
};

const gen = (dirName) => {
	return { type: "autogenerated", dirName };
};

export default {
	main: [back, hr, gen(".")],
};
